# Generated by Django 5.0.4 on 2024-05-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_songs_albom_alter_songs_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cover', models.URLField(null=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('create_data', models.DateField(auto_now_add=True)),
                ('albom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.songs')),
            ],
        ),
    ]
