# Generated by Django 5.0.4 on 2024-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_country_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albom',
            name='cover',
        ),
        migrations.AddField(
            model_name='albom',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
