# Generated by Django 5.0.4 on 2024-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_cover_country_address_remove_albom_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
